//Half generative art/Sound visual the art is generated by the voices around it 


var mic;
var frameCount


function setup() {
  createCanvas(400, 400);
  mic = new p5.AudioIn();
  mic.start();
  rectMode(CENTER);
  angleMode(DEGREES);
  //fill= (random(255),random(255),random(255))
}

function draw() {
  background(0,1);
  noStroke();
fill(random(225),random(225),random(225));
  translate(200,200);
  var vol= mic.getLevel();
  rotate(frameCount);
  
  rect(vol*2000,vol*2000,vol*2000,vol*2000)
  
  frameCount=frameCount+2
  
}